// <auto-generated>
// Generated by tools/gen-livelink-native.py from the csbindgen output (function pointers instead of DllImport).
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace Yozolab.YoluPainter.Editor.LiveLink
{
    internal static unsafe partial class LiveLinkNative
    {





        /// <summary>
        ///  この口の版（最初に呼ぶ。C# の知っている版と違えば、ほかの関数を呼ばない）。
        /// </summary>
        internal static uint ylb_abi_version() => ((delegate* unmanaged[Cdecl]<uint>)Pointer(p_ylb_abi_version))();
        static IntPtr p_ylb_abi_version;

        /// <summary>
        ///  読めるプロトコルの版（上の 16 ビットが一番古い版、下の 16 ビットが一番新しい版）。
        /// </summary>
        internal static uint ylb_protocol_versions() => ((delegate* unmanaged[Cdecl]<uint>)Pointer(p_ylb_protocol_versions))();
        static IntPtr p_ylb_protocol_versions;

        /// <summary>
        ///  つなぎ始める（すぐに返る。つながったかは ylb_status と知らせで見る）。返すのはつながりの番号（0 は名前が使えない）。
        /// </summary>
        internal static ulong ylb_connect(byte* name, int name_len, byte* agent, int agent_len) => ((delegate* unmanaged[Cdecl]<byte*, int, byte*, int, ulong>)Pointer(p_ylb_connect))(name, name_len, agent, agent_len);
        static IntPtr p_ylb_connect;

        /// <summary>
        ///  `ylb_connect`（自分のアプリの版を挨拶で名乗る。Unity のパッケージの版の文字列「0.3.0」など。読めない・空なら名乗らない）。
        /// </summary>
        internal static ulong ylb_connect_with(byte* name, int name_len, byte* agent, int agent_len, byte* app_version, int app_version_len) => ((delegate* unmanaged[Cdecl]<byte*, int, byte*, int, byte*, int, ulong>)Pointer(p_ylb_connect_with))(name, name_len, agent, agent_len, app_version, app_version_len);
        static IntPtr p_ylb_connect_with;

        /// <summary>
        ///  切る（Bye を送る。共有メモリの写像を手放す）。番号はもう使えない。
        /// </summary>
        internal static int ylb_disconnect(ulong handle) => ((delegate* unmanaged[Cdecl]<ulong, int>)Pointer(p_ylb_disconnect))(handle);
        static IntPtr p_ylb_disconnect;

        /// <summary>
        ///  全部のつながりを切る（ドメインの読み直しの後に、前のドメインのつながりを片付ける）。切った数を返す。
        /// </summary>
        internal static int ylb_disconnect_all() => ((delegate* unmanaged[Cdecl]<int>)Pointer(p_ylb_disconnect_all))();
        static IntPtr p_ylb_disconnect_all;

        /// <summary>
        ///  状態: 0 = つないでいる、1 = つながった、2 = 閉じた、3 = 失敗。
        /// </summary>
        internal static int ylb_status(ulong handle) => ((delegate* unmanaged[Cdecl]<ulong, int>)Pointer(p_ylb_status))(handle);
        static IntPtr p_ylb_status;

        /// <summary>
        ///  状態の説明（UTF-8）。要る長さを返す。
        /// </summary>
        internal static int ylb_status_text(ulong handle, byte* buf, int cap) => ((delegate* unmanaged[Cdecl]<ulong, byte*, int, int>)Pointer(p_ylb_status_text))(handle, buf, cap);
        static IntPtr p_ylb_status_text;

        /// <summary>
        ///  何かが変わるたびに増える番号（C# は変わっていなければ何もしない）。
        /// </summary>
        internal static ulong ylb_serial(ulong handle) => ((delegate* unmanaged[Cdecl]<ulong, ulong>)Pointer(p_ylb_serial))(handle);
        static IntPtr p_ylb_serial;

        /// <summary>
        ///  このつながりで使える機能の印（双方が出した印の共通部分。つながるまでは 0）。印の要る新しい命令は、ここに立っているときだけ送る。
        /// </summary>
        internal static ulong ylb_common_features(ulong handle) => ((delegate* unmanaged[Cdecl]<ulong, ulong>)Pointer(p_ylb_common_features))(handle);
        static IntPtr p_ylb_common_features;

        /// <summary>
        ///  相手（スタンドアロン）のアプリの版（`major &lt;&lt; 32 | minor &lt;&lt; 16 | patch`）。つながっていない・版を名乗らない古い相手は `u64::MAX`。
        /// </summary>
        internal static ulong ylb_peer_app_version(ulong handle) => ((delegate* unmanaged[Cdecl]<ulong, ulong>)Pointer(p_ylb_peer_app_version))(handle);
        static IntPtr p_ylb_peer_app_version;

        /// <summary>
        ///  版のずれと機能の印の様子を取り出す。返すのは `state`（0 = まだ無い、1 = つながった、2 = 版の範囲が合わず断られた）、負は失敗。
        /// </summary>
        internal static int ylb_link_report(ulong handle, YlbLinkReport* report) => ((delegate* unmanaged[Cdecl]<ulong, YlbLinkReport*, int>)Pointer(p_ylb_link_report))(handle, report);
        static IntPtr p_ylb_link_report;

        /// <summary>
        ///  知らせを 1 つ取り出す。取り出せば 1、無ければ 0。
        /// </summary>
        internal static int ylb_next_event(ulong handle, YlbEvent* @event, byte* buf, int cap) => ((delegate* unmanaged[Cdecl]<ulong, YlbEvent*, byte*, int, int>)Pointer(p_ylb_next_event))(handle, @event, buf, cap);
        static IntPtr p_ylb_next_event;

        /// <summary>
        ///  モデルの組み立てを始める（前の組み立ては捨てる）。
        /// </summary>
        internal static int ylb_model_begin(ulong handle, byte* name, int name_len) => ((delegate* unmanaged[Cdecl]<ulong, byte*, int, int>)Pointer(p_ylb_model_begin))(handle, name, name_len);
        static IntPtr p_ylb_model_begin;

        /// <summary>
        ///  マテリアルの組を足す。unassigned が 0 でなければマテリアルの無いスロットの組（名前・GUID は使わない）。guid_len が 0 ならアセットでない。
        ///  返すのはマテリアルの番号。
        /// </summary>
        internal static int ylb_model_material(ulong handle, int unassigned, byte* name, int name_len, byte* guid, int guid_len, long file_id, byte* shader, int shader_len) => ((delegate* unmanaged[Cdecl]<ulong, int, byte*, int, byte*, int, long, byte*, int, int>)Pointer(p_ylb_model_material))(handle, unassigned, name, name_len, guid, guid_len, file_id, shader, shader_len);
        static IntPtr p_ylb_model_material;

        /// <summary>
        ///  マテリアルのシェーダーの 2D テクスチャのプロパティと、今入っているテクスチャの大きさ（無ければ 0）を足す。
        /// </summary>
        internal static int ylb_model_material_texture(ulong handle, int material, byte* name, int name_len, uint width, uint height) => ((delegate* unmanaged[Cdecl]<ulong, int, byte*, int, uint, uint, int>)Pointer(p_ylb_model_material_texture))(handle, material, name, name_len, width, height);
        static IntPtr p_ylb_model_material_texture;

        /// <summary>
        ///  Unity 側が見せられるチャンネルと流し込み先のプロパティを足す。
        /// </summary>
        internal static int ylb_model_material_route(ulong handle, int material, int channel, byte* property, int property_len) => ((delegate* unmanaged[Cdecl]<ulong, int, int, byte*, int, int>)Pointer(p_ylb_model_material_route))(handle, material, channel, property, property_len);
        static IntPtr p_ylb_model_material_route;

        /// <summary>
        ///  メッシュを足す（位置は根のローカルの空間。法線・UV0 は null なら無し）。返すのはメッシュの番号。
        /// </summary>
        internal static int ylb_model_mesh(ulong handle, byte* key, int key_len, byte* name, int name_len, int skinned, float* positions, float* normals, float* uv0, int vertex_count) => ((delegate* unmanaged[Cdecl]<ulong, byte*, int, byte*, int, int, float*, float*, float*, int, int>)Pointer(p_ylb_model_mesh))(handle, key, key_len, name, name_len, skinned, positions, normals, uv0, vertex_count);
        static IntPtr p_ylb_model_mesh;

        /// <summary>
        ///  メッシュに三角形の組を足す（添字は 3 つずつ、頂点の数より小さい）。
        /// </summary>
        internal static int ylb_model_submesh(ulong handle, int mesh, int material, int* indices, int index_count) => ((delegate* unmanaged[Cdecl]<ulong, int, int, int*, int, int>)Pointer(p_ylb_model_submesh))(handle, mesh, material, indices, index_count);
        static IntPtr p_ylb_model_submesh;

        /// <summary>
        ///  組み立てたモデルを送る（積むだけ）。返すのはモデルの世代（1 から）。送りの列が混んでいれば YLB_E_BUSY（組み立てを残すので、少し後にもう一度呼べる。断るときはモデルを枠にしないので、呼び直しは安い）。
        /// </summary>
        internal static int ylb_model_send(ulong handle) => ((delegate* unmanaged[Cdecl]<ulong, int>)Pointer(p_ylb_model_send))(handle);
        static IntPtr p_ylb_model_send;

        /// <summary>
        ///  送ったモデルを閉じる（スタンドアロンにもう見せないと知らせる）。
        /// </summary>
        internal static int ylb_model_close(ulong handle) => ((delegate* unmanaged[Cdecl]<ulong, int>)Pointer(p_ylb_model_close))(handle);
        static IntPtr p_ylb_model_close;

        /// <summary>
        ///  マテリアルの更新の組み立てを始める（前の組み立ては捨てる）。送ったモデルがあるときだけ。足すマテリアルの数と並びは、送ったモデルと同じにする。
        /// </summary>
        internal static int ylb_materials_begin(ulong handle) => ((delegate* unmanaged[Cdecl]<ulong, int>)Pointer(p_ylb_materials_begin))(handle);
        static IntPtr p_ylb_materials_begin;

        /// <summary>
        ///  更新のマテリアルの組を足す（`ylb_model_material` と同じ引数）。返すのはマテリアルの番号。
        /// </summary>
        internal static int ylb_materials_material(ulong handle, int unassigned, byte* name, int name_len, byte* guid, int guid_len, long file_id, byte* shader, int shader_len) => ((delegate* unmanaged[Cdecl]<ulong, int, byte*, int, byte*, int, long, byte*, int, int>)Pointer(p_ylb_materials_material))(handle, unassigned, name, name_len, guid, guid_len, file_id, shader, shader_len);
        static IntPtr p_ylb_materials_material;

        /// <summary>
        ///  更新のマテリアルにテクスチャのプロパティを足す。
        /// </summary>
        internal static int ylb_materials_texture(ulong handle, int material, byte* name, int name_len, uint width, uint height) => ((delegate* unmanaged[Cdecl]<ulong, int, byte*, int, uint, uint, int>)Pointer(p_ylb_materials_texture))(handle, material, name, name_len, width, height);
        static IntPtr p_ylb_materials_texture;

        /// <summary>
        ///  更新のマテリアルに、見せられるチャンネルと流し込み先を足す。
        /// </summary>
        internal static int ylb_materials_route(ulong handle, int material, int channel, byte* property, int property_len) => ((delegate* unmanaged[Cdecl]<ulong, int, int, byte*, int, int>)Pointer(p_ylb_materials_route))(handle, material, channel, property, property_len);
        static IntPtr p_ylb_materials_route;

        /// <summary>
        ///  組み立てたマテリアルの更新を送る（積むだけ）。マテリアルの数は送ったモデルと同じでなければならない（違えば YLB_E_ARGUMENT）。返すのはマテリアルの数。
        ///  送りの列が混んでいれば YLB_E_BUSY（組み立てを残すので、少し後にもう一度呼べる）。同じ世代の送っていない古い更新は置き換わる。
        /// </summary>
        internal static int ylb_materials_send(ulong handle) => ((delegate* unmanaged[Cdecl]<ulong, int>)Pointer(p_ylb_materials_send))(handle);
        static IntPtr p_ylb_materials_send;

        /// <summary>
        ///  ポーズの組み立てを始める。
        /// </summary>
        internal static int ylb_pose_begin(ulong handle) => ((delegate* unmanaged[Cdecl]<ulong, int>)Pointer(p_ylb_pose_begin))(handle);
        static IntPtr p_ylb_pose_begin;

        /// <summary>
        ///  メッシュの新しい形を足す（頂点の数は送ったモデルのそのメッシュと同じ）。
        /// </summary>
        internal static int ylb_pose_mesh(ulong handle, int mesh, float* positions, float* normals, int vertex_count) => ((delegate* unmanaged[Cdecl]<ulong, int, float*, float*, int, int>)Pointer(p_ylb_pose_mesh))(handle, mesh, positions, normals, vertex_count);
        static IntPtr p_ylb_pose_mesh;

        /// <summary>
        ///  組み立てたポーズを送る（積むだけ。同じメッシュのまだ送っていない古いポーズは置き換える）。返すのは足したメッシュの数。
        /// </summary>
        internal static int ylb_pose_send(ulong handle) => ((delegate* unmanaged[Cdecl]<ulong, int>)Pointer(p_ylb_pose_send))(handle);
        static IntPtr p_ylb_pose_send;

        /// <summary>
        ///  マテリアルの値の組み立てを始める（前の組み立ては捨てる）。送ったモデルがあるときだけ。`material` は送ったモデルのマテリアルの番号、
        ///  `kind` は 0 = 値なし（前に送った値を捨てさせる）・1 = lilToon、`source` は何の対応と確かめたかの文（人に見せるだけ）。
        /// </summary>
        internal static int ylb_values_begin(ulong handle, int material, int kind, byte* shader, int shader_len, byte* source, int source_len) => ((delegate* unmanaged[Cdecl]<ulong, int, int, byte*, int, byte*, int, int>)Pointer(p_ylb_values_begin))(handle, material, kind, shader, shader_len, source, source_len);
        static IntPtr p_ylb_values_begin;

        /// <summary>
        ///  Float・Range の値を足す（有限の数だけ）。
        /// </summary>
        internal static int ylb_values_float(ulong handle, byte* name, int name_len, float value) => ((delegate* unmanaged[Cdecl]<ulong, byte*, int, float, int>)Pointer(p_ylb_values_float))(handle, name, name_len, value);
        static IntPtr p_ylb_values_float;

        /// <summary>
        ///  Integer の値を足す。
        /// </summary>
        internal static int ylb_values_int(ulong handle, byte* name, int name_len, int value) => ((delegate* unmanaged[Cdecl]<ulong, byte*, int, int, int>)Pointer(p_ylb_values_int))(handle, name, name_len, value);
        static IntPtr p_ylb_values_int;

        /// <summary>
        ///  色の値を足す（マテリアルに入っているままの値。`[HDR]` でない色はガンマの空間）。
        /// </summary>
        internal static int ylb_values_color(ulong handle, byte* name, int name_len, float r, float g, float b, float a) => ((delegate* unmanaged[Cdecl]<ulong, byte*, int, float, float, float, float, int>)Pointer(p_ylb_values_color))(handle, name, name_len, r, g, b, a);
        static IntPtr p_ylb_values_color;

        /// <summary>
        ///  ベクトルの値を足す（テクスチャのタイリング・オフセットは `&lt;名前&gt;_ST` の名前で）。
        /// </summary>
        internal static int ylb_values_vector(ulong handle, byte* name, int name_len, float x, float y, float z, float w) => ((delegate* unmanaged[Cdecl]<ulong, byte*, int, float, float, float, float, int>)Pointer(p_ylb_values_vector))(handle, name, name_len, x, y, z, w);
        static IntPtr p_ylb_values_vector;

        /// <summary>
        ///  有効なキーワードを足す（重ねて足したものは 1 つ）。
        /// </summary>
        internal static int ylb_values_keyword(ulong handle, byte* name, int name_len) => ((delegate* unmanaged[Cdecl]<ulong, byte*, int, int>)Pointer(p_ylb_values_keyword))(handle, name, name_len);
        static IntPtr p_ylb_values_keyword;

        /// <summary>
        ///  描いていないスロットの様子を足す。`state`: 0 入っていない・1 絵を送る（この値を送った後に ylb_texture_send）・2 前に送った絵と同じ・
        ///  3 予算を超えて送らない・4 読めない。`width`・`height` は元のテクスチャの大きさ。
        /// </summary>
        internal static int ylb_values_slot(ulong handle, byte* name, int name_len, int state, uint width, uint height) => ((delegate* unmanaged[Cdecl]<ulong, byte*, int, int, uint, uint, int>)Pointer(p_ylb_values_slot))(handle, name, name_len, state, width, height);
        static IntPtr p_ylb_values_slot;

        /// <summary>
        ///  組み立てた値を送る（積むだけ）。返すのは 1 = 積んだ、0 = スタンドアロンに印（MATERIAL_VALUES）が無いので送らない（組み立ては捨てる）。
        ///  送りの列が混んでいれば YLB_E_BUSY（組み立てを残すので、少し後にもう一度呼べる）。同じマテリアルの送っていない古い値と絵は置き換わる
        ///  （新しい値が「前と同じ」と言う絵が列の中にあるときを除く）。
        /// </summary>
        internal static int ylb_values_send(ulong handle) => ((delegate* unmanaged[Cdecl]<ulong, int>)Pointer(p_ylb_values_send))(handle);
        static IntPtr p_ylb_values_send;

        /// <summary>
        ///  描いていないスロットの絵を送る（積むだけ。直前の値で状態 1 と言ったスロット）。`pixels` は RGBA8（straight）で行は下から、
        ///  `pixel_len` は幅 × 高さ × 4。辺は MAX_SLOT_TEXTURE_SIZE まで（送る側が縮める）。`srgb` が 0 でなければ Unity はこの絵を sRGB として
        ///  読む。返すのは 1 = 積んだ、0 = スタンドアロンに印が無いので送らない。
        ///  送りの列が混んでいれば YLB_E_BUSY（呼び手が画素を持っていて、少し後に送り直す。同じ世代・マテリアル・スロットの送っていない古い絵は置き換わる）。
        /// </summary>
        internal static int ylb_texture_send(ulong handle, int material, byte* slot, int slot_len, uint width, uint height, int srgb, byte* pixels, int pixel_len) => ((delegate* unmanaged[Cdecl]<ulong, int, byte*, int, uint, uint, int, byte*, int, int>)Pointer(p_ylb_texture_send))(handle, material, slot, slot_len, width, height, srgb, pixels, pixel_len);
        static IntPtr p_ylb_texture_send;

        /// <summary>
        ///  元の絵を送る（積むだけ）。Color の流し込み先のスロットの元のテクスチャ 1 つ（直前のモデルのマテリアルで絵が入っているもの）。
        ///  `state` は 0 = 絵が付く・1 = 読めない・2 = 辺が上限を超える・3 = 全部の絵の予算を超える（1〜3 は画素なし。`width`・`height` は元の
        ///  テクスチャの大きさ）、`read` は 0 = 原本のファイル・1 = 取り込んだ絵の CPU の値・2 = GPU を通して、`flags` の bit0 は圧縮された
        ///  テクスチャから読んだ。`pixels` は RGBA8（straight）で行は下から、`pixel_len` は幅 × 高さ × 4（辺は MAX_ORIGINAL_SIZE まで）。
        ///  `srgb` が 0 でなければ Unity はこの絵を sRGB として読む（ガンマの色空間のプロジェクトは真で送る）。
        ///  `stamp` はこの絵の印（Unity が決める 64 ビット。0 は印なし）。`state` が 4（スタンドアロンが頼みで持つと言った絵と印が同じ。画素なし）のときは
        ///  0 以外が要る（`width`・`height` は Unity のテクスチャの大きさ）。
        ///  返すのは 1 = 積んだ、0 = スタンドアロンに印が無いので送らない。送りの列が混んでいれば YLB_E_BUSY（呼び手が画素を持っていて、少し後に送り直す。
        ///  画素の付いた元の絵は、同じ世代・マテリアル・スロットの送っていない古い元の絵を置き換える）。大きな絵は、読む前に `ylb_send_room` で入るかを確かめる。
        /// </summary>
        internal static int ylb_original_send(ulong handle, int material, byte* slot, int slot_len, int state, int read, int flags, uint width, uint height, int srgb, ulong stamp, byte* pixels, int pixel_len) => ((delegate* unmanaged[Cdecl]<ulong, int, byte*, int, int, int, int, uint, uint, int, ulong, byte*, int, int>)Pointer(p_ylb_original_send))(handle, material, slot, slot_len, state, read, flags, width, height, srgb, stamp, pixels, pixel_len);
        static IntPtr p_ylb_original_send;

        /// <summary>
        ///  試験用: 1 つの命令の中身の上限（バイト）を狭める（`MAX_PAYLOAD` より大きくはならない）。巨大なモデルを作らずに、上限を超える
        ///  モデルの断り（YLB_E_TOO_LARGE）を確かめる。
        /// </summary>
        internal static int ylb_test_set_payload_limit(ulong handle, ulong bytes) => ((delegate* unmanaged[Cdecl]<ulong, ulong, int>)Pointer(p_ylb_test_set_payload_limit))(handle, bytes);
        static IntPtr p_ylb_test_set_payload_limit;

        /// <summary>
        ///  試験用: 送りの列の上限（バイト）を決める（既定は 256 MiB）。小さい量で「混んでいる」（YLB_E_BUSY）を確かめる。
        /// </summary>
        internal static int ylb_test_set_outbox_limit(ulong handle, ulong bytes) => ((delegate* unmanaged[Cdecl]<ulong, ulong, int>)Pointer(p_ylb_test_set_outbox_limit))(handle, bytes);
        static IntPtr p_ylb_test_set_outbox_limit;

        /// <summary>
        ///  スタンドアロンからの頼みを 1 つ取り出す（待たない）。1 = 取り出した（`request` と、スロットの名前を `slot` へ UTF-8 で。入りきらなければ
        ///  文字の途中で切って、`slot_len` に要る長さ）、0 = 頼みは無い、負は失敗。頼みはスタンドアロンが印（MATERIAL_REQUEST）を名乗り、こちらも
        ///  名乗っているときだけ来る。同じマテリアルの同じ頼みは 1 つにまとまる。
        ///
        ///  # Safety
        ///  `request` は 1 つ分の領域、`slot` は `slot_cap` バイトの書ける領域（または null）を指すこと。
        /// </summary>
        internal static int ylb_next_request(ulong handle, YlbRequest* request, byte* slot, int slot_cap) => ((delegate* unmanaged[Cdecl]<ulong, YlbRequest*, byte*, int, int>)Pointer(p_ylb_next_request))(handle, request, slot, slot_cap);
        static IntPtr p_ylb_next_request;

        /// <summary>
        ///  まだ送り終えていない命令のバイトの合計（順番待ちに積んだものと、いま書いている途中のもの）。大きな絵を続けて送るとき、これが小さくなるまで
        ///  次を積まないための目安。
        /// </summary>
        internal static ulong ylb_pending_bytes(ulong handle) => ((delegate* unmanaged[Cdecl]<ulong, ulong>)Pointer(p_ylb_pending_bytes))(handle);
        static IntPtr p_ylb_pending_bytes;

        /// <summary>
        ///  いま積める大きさの目安（バイト）。送りの列の上限（256 MiB）から、積んである量を引いたもの。何も積んでいなければ、1 つの命令が上限より大きくても
        ///  入るので `u64::MAX`。数が合わないハンドルは 0。C# は、大きな絵を読む前にこれで足りるかを見て、足りなければ読まずに待つ（Unity の主のスレッドは
        ///  待たない）。置き換えで空く分は数えないので、足りなくても `ylb_*_send` が積めることはある。
        /// </summary>
        internal static ulong ylb_send_room(ulong handle) => ((delegate* unmanaged[Cdecl]<ulong, ulong>)Pointer(p_ylb_send_room))(handle);
        static IntPtr p_ylb_send_room;

        /// <summary>
        ///  テクスチャセットの数。
        /// </summary>
        internal static int ylb_set_count(ulong handle) => ((delegate* unmanaged[Cdecl]<ulong, int>)Pointer(p_ylb_set_count))(handle);
        static IntPtr p_ylb_set_count;

        /// <summary>
        ///  index 番目（セットの番号の順）のテクスチャセットの情報。
        /// </summary>
        internal static int ylb_set_info(ulong handle, int index, YlbSetInfo* info) => ((delegate* unmanaged[Cdecl]<ulong, int, YlbSetInfo*, int>)Pointer(p_ylb_set_info))(handle, index, info);
        static IntPtr p_ylb_set_info;

        /// <summary>
        ///  テクスチャセットの名前。要る長さを返す。
        /// </summary>
        internal static int ylb_set_name(ulong handle, uint set, byte* buf, int cap) => ((delegate* unmanaged[Cdecl]<ulong, uint, byte*, int, int>)Pointer(p_ylb_set_name))(handle, set, buf, cap);
        static IntPtr p_ylb_set_name;

        /// <summary>
        ///  チャンネルの汚れたタイルの数。
        /// </summary>
        internal static int ylb_channel_dirty(ulong handle, uint set, int channel) => ((delegate* unmanaged[Cdecl]<ulong, uint, int, int>)Pointer(p_ylb_channel_dirty))(handle, set, channel);
        static IntPtr p_ylb_channel_dirty;

        /// <summary>
        ///  チャンネルの全部のタイルを汚れたことにする（Unity 側のテクスチャを作り直した・失ったとき、次の ylb_copy_dirty で全面を写し直す）。
        /// </summary>
        internal static int ylb_channel_mark_all_dirty(ulong handle, uint set, int channel) => ((delegate* unmanaged[Cdecl]<ulong, uint, int, int>)Pointer(p_ylb_channel_mark_all_dirty))(handle, set, channel);
        static IntPtr p_ylb_channel_mark_all_dirty;

        /// <summary>
        ///  汚れたタイルを image（幅 × 高さ × 4 バイト、straight RGBA8、下の行から。Unity の Texture2D の RGBA32 の生の並び）へ写す。
        ///  strip が null でなければ、strip_tiles 個までのタイルを帯（幅 strip_tiles × タイル、高さ タイル、下の行から）にも並べ、
        ///  coords（2 × strip_tiles 個）にタイルの座標を書いて、そこで止める（残りは次に）。返すのは写したタイルの数。
        ///  image は null でもよい（strip が要る）: 全体を GPU のテクスチャ（RenderTexture）に持つ側が、CPU に全体の写しを持たずに帯だけを受ける。
        /// </summary>
        internal static int ylb_copy_dirty(ulong handle, uint set, int channel, byte* image, ulong image_len, byte* strip, ulong strip_len, int strip_tiles, uint* coords, YlbCopyResult* result) => ((delegate* unmanaged[Cdecl]<ulong, uint, int, byte*, ulong, byte*, ulong, int, uint*, YlbCopyResult*, int>)Pointer(p_ylb_copy_dirty))(handle, set, channel, image, image_len, strip, strip_len, strip_tiles, coords, result);
        static IntPtr p_ylb_copy_dirty;

        /// <summary>
        ///  UNIX 時刻のマイクロ秒（スタンドアロン・ブリッジと同じ時計で遅れを測る）。
        /// </summary>
        internal static ulong ylb_now_us() => ((delegate* unmanaged[Cdecl]<ulong>)Pointer(p_ylb_now_us))();
        static IntPtr p_ylb_now_us;

        /// <summary>
        ///  試しの模様を返すスタンドアロンを、このプロセスの中で待ち受けさせる。モデルが来ると、マテリアルごとに size × size のセット
        ///  （Color と、流し込み先のあるチャンネル）を作り、ylb_test_server_pattern の模様を全部のタイルに書いて知らせる。返すのは番号（0 は失敗）。
        /// </summary>
        internal static ulong ylb_test_server_start(byte* name, int name_len, int size, int tile_size) => ((delegate* unmanaged[Cdecl]<byte*, int, int, int, ulong>)Pointer(p_ylb_test_server_start))(name, name_len, size, tile_size);
        static IntPtr p_ylb_test_server_start;

        /// <summary>
        ///  自己診断のスタンドアロンが、つながりから読むのを止める（`paused` が 0 以外）か、再び読む（0）。止めている間、相手の書く枠は溜まり、ブリッジの
        ///  送りの列は読まれない相手の様子になる（上限と「混んでいる」の確かめ用）。
        /// </summary>
        internal static int ylb_test_server_pause_reading(ulong server, int paused) => ((delegate* unmanaged[Cdecl]<ulong, int, int>)Pointer(p_ylb_test_server_pause_reading))(server, paused);
        static IntPtr p_ylb_test_server_pause_reading;

        /// <summary>
        ///  自己診断のスタンドアロンを止める（つないでいる側を先に切る。Windows では相手が切るまで読むスレッドが残る）。
        /// </summary>
        internal static int ylb_test_server_stop(ulong server) => ((delegate* unmanaged[Cdecl]<ulong, int>)Pointer(p_ylb_test_server_stop))(server);
        static IntPtr p_ylb_test_server_stop;

        /// <summary>
        ///  模様の色（RGBA を r | g &lt;&lt; 8 | b &lt;&lt; 16 | a &lt;&lt; 24 に詰めたもの）: マテリアルの番号ごとの色の市松（奇数のタイルは半分の明るさ）。
        /// </summary>
        internal static uint ylb_test_server_pattern(uint material, uint tile_x, uint tile_y) => ((delegate* unmanaged[Cdecl]<uint, uint, uint, uint>)Pointer(p_ylb_test_server_pattern))(material, tile_x, tile_y);
        static IntPtr p_ylb_test_server_pattern;

        /// <summary>
        ///  自己診断のスタンドアロンで、material の番号のセットの channel の、タイル [x0, x1) × [y0, y1) を色 rgba（ylb_test_server_pattern
        ///  と同じ詰め方）で塗り、変わったタイルを知らせる。返すのは塗ったタイルの数。
        /// </summary>
        internal static int ylb_test_server_paint(ulong server, uint material, int channel, uint x0, uint y0, uint x1, uint y1, uint rgba) => ((delegate* unmanaged[Cdecl]<ulong, uint, int, uint, uint, uint, uint, uint, int>)Pointer(p_ylb_test_server_paint))(server, material, channel, x0, y0, x1, y1, rgba);
        static IntPtr p_ylb_test_server_paint;

        /// <summary>
        ///  自己診断のスタンドアロンの鍵のファイルを、別の鍵に差し替える（つなぎ直すブリッジは、鍵の合わない断りを受ける）。
        /// </summary>
        internal static int ylb_test_server_replace_key(ulong server) => ((delegate* unmanaged[Cdecl]<ulong, int>)Pointer(p_ylb_test_server_replace_key))(server);
        static IntPtr p_ylb_test_server_replace_key;

        /// <summary>
        ///  自己診断のスタンドアロンの名乗りを決める（次につなぐブリッジから効く）。`app_version`・`min_peer` は `major &lt;&lt; 32 | minor &lt;&lt; 16 | patch`
        ///  （`u64::MAX` は版を名乗らない古いスタンドアロンの役）、`features` は出す機能の印。既定はこの DLL の版・要求なし・印なし。
        /// </summary>
        internal static int ylb_test_server_configure(ulong server, ulong app_version, ulong min_peer, ulong features) => ((delegate* unmanaged[Cdecl]<ulong, ulong, ulong, ulong, int>)Pointer(p_ylb_test_server_configure))(server, app_version, min_peer, features);
        static IntPtr p_ylb_test_server_configure;

        /// <summary>
        ///  自己診断のスタンドアロンの読めるプロトコルの版の範囲を決める（次につなぐブリッジから効く。ブリッジの範囲と重ならなければ、版の範囲の断りを返す）。
        /// </summary>
        internal static int ylb_test_server_set_protocol(ulong server, uint min, uint max) => ((delegate* unmanaged[Cdecl]<ulong, uint, uint, int>)Pointer(p_ylb_test_server_set_protocol))(server, min, max);
        static IntPtr p_ylb_test_server_set_protocol;

        /// <summary>
        ///  自己診断のスタンドアロンが受けたものの数。
        /// </summary>
        internal static int ylb_test_server_stats(ulong server, YlbTestServerStats* stats) => ((delegate* unmanaged[Cdecl]<ulong, YlbTestServerStats*, int>)Pointer(p_ylb_test_server_stats))(server, stats);
        static IntPtr p_ylb_test_server_stats;

        /// <summary>
        ///  自己診断のスタンドアロンが最後に受けた、マテリアル `material` の値のプロパティ `name` を `out`（4 つの f32。数は x、Int は x に
        ///  数として）へ写す。返すのは型（0 Float・1 Int・2 Color・3 Vector）、無ければ YLB_E_ARGUMENT。
        /// </summary>
        internal static int ylb_test_server_value(ulong server, uint material, byte* name, int name_len, float* @out) => ((delegate* unmanaged[Cdecl]<ulong, uint, byte*, int, float*, int>)Pointer(p_ylb_test_server_value))(server, material, name, name_len, @out);
        static IntPtr p_ylb_test_server_value;

        /// <summary>
        ///  自己診断のスタンドアロンが最後に受けた、マテリアル `material` のスロット `name` の様子（0〜4。`ylb_values_slot` と同じ番号）。
        ///  キーワードを引くときは `keyword` を 0 でなくする（あれば 1、無ければ 0）。値が無ければ YLB_E_ARGUMENT。
        /// </summary>
        internal static int ylb_test_server_slot(ulong server, uint material, byte* name, int name_len, int keyword) => ((delegate* unmanaged[Cdecl]<ulong, uint, byte*, int, int, int>)Pointer(p_ylb_test_server_slot))(server, material, name, name_len, keyword);
        static IntPtr p_ylb_test_server_slot;

        /// <summary>
        ///  自己診断のスタンドアロンが最後に受けた、マテリアル `material` のスロット `slot` の元の絵の様子。無ければ YLB_E_ARGUMENT。
        /// </summary>
        internal static int ylb_test_server_original(ulong server, uint material, byte* slot, int slot_len, YlbTestServerOriginal* @out) => ((delegate* unmanaged[Cdecl]<ulong, uint, byte*, int, YlbTestServerOriginal*, int>)Pointer(p_ylb_test_server_original))(server, material, slot, slot_len, @out);
        static IntPtr p_ylb_test_server_original;

        /// <summary>
        ///  自己診断のスタンドアロンから、つながっているブリッジへ頼みを 1 つ送る（スタンドアロンが頼む役）。`generation` が 0 なら今のモデルの世代、
        ///  `wants` は bit0 値・bit1 元の絵、`slot` は元の絵のスロット（値だけなら空でよい）、`have` は手元の絵の印（0 は持たない）。
        ///  相手に印（MATERIAL_REQUEST）が無い・つながっていなければ YLB_E_STATE。
        /// </summary>
        internal static int ylb_test_server_request(ulong server, uint generation, uint material, int wants, byte* slot, int slot_len, ulong have) => ((delegate* unmanaged[Cdecl]<ulong, uint, uint, int, byte*, int, ulong, int>)Pointer(p_ylb_test_server_request))(server, generation, material, wants, slot, slot_len, have);
        static IntPtr p_ylb_test_server_request;

        /// <summary>
        ///  自己診断のスタンドアロンが最後に受けた、マテリアル `material` のスロット `slot` の絵の様子。無ければ YLB_E_ARGUMENT。
        /// </summary>
        internal static int ylb_test_server_texture(ulong server, uint material, byte* slot, int slot_len, YlbTestServerTexture* @out) => ((delegate* unmanaged[Cdecl]<ulong, uint, byte*, int, YlbTestServerTexture*, int>)Pointer(p_ylb_test_server_texture))(server, material, slot, slot_len, @out);
        static IntPtr p_ylb_test_server_texture;



        /// <summary>ライブラリの関数の番地を結ぶ（<paramref name="symbol"/> は、名前から番地を引く。無い関数があれば EntryPointNotFoundException）。</summary>
        internal static void Bind(Func<string, IntPtr> symbol)
        {
            p_ylb_abi_version = Resolve(symbol, "ylb_abi_version");
            p_ylb_protocol_versions = Resolve(symbol, "ylb_protocol_versions");
            p_ylb_connect = Resolve(symbol, "ylb_connect");
            p_ylb_connect_with = Resolve(symbol, "ylb_connect_with");
            p_ylb_disconnect = Resolve(symbol, "ylb_disconnect");
            p_ylb_disconnect_all = Resolve(symbol, "ylb_disconnect_all");
            p_ylb_status = Resolve(symbol, "ylb_status");
            p_ylb_status_text = Resolve(symbol, "ylb_status_text");
            p_ylb_serial = Resolve(symbol, "ylb_serial");
            p_ylb_common_features = Resolve(symbol, "ylb_common_features");
            p_ylb_peer_app_version = Resolve(symbol, "ylb_peer_app_version");
            p_ylb_link_report = Resolve(symbol, "ylb_link_report");
            p_ylb_next_event = Resolve(symbol, "ylb_next_event");
            p_ylb_model_begin = Resolve(symbol, "ylb_model_begin");
            p_ylb_model_material = Resolve(symbol, "ylb_model_material");
            p_ylb_model_material_texture = Resolve(symbol, "ylb_model_material_texture");
            p_ylb_model_material_route = Resolve(symbol, "ylb_model_material_route");
            p_ylb_model_mesh = Resolve(symbol, "ylb_model_mesh");
            p_ylb_model_submesh = Resolve(symbol, "ylb_model_submesh");
            p_ylb_model_send = Resolve(symbol, "ylb_model_send");
            p_ylb_model_close = Resolve(symbol, "ylb_model_close");
            p_ylb_materials_begin = Resolve(symbol, "ylb_materials_begin");
            p_ylb_materials_material = Resolve(symbol, "ylb_materials_material");
            p_ylb_materials_texture = Resolve(symbol, "ylb_materials_texture");
            p_ylb_materials_route = Resolve(symbol, "ylb_materials_route");
            p_ylb_materials_send = Resolve(symbol, "ylb_materials_send");
            p_ylb_pose_begin = Resolve(symbol, "ylb_pose_begin");
            p_ylb_pose_mesh = Resolve(symbol, "ylb_pose_mesh");
            p_ylb_pose_send = Resolve(symbol, "ylb_pose_send");
            p_ylb_values_begin = Resolve(symbol, "ylb_values_begin");
            p_ylb_values_float = Resolve(symbol, "ylb_values_float");
            p_ylb_values_int = Resolve(symbol, "ylb_values_int");
            p_ylb_values_color = Resolve(symbol, "ylb_values_color");
            p_ylb_values_vector = Resolve(symbol, "ylb_values_vector");
            p_ylb_values_keyword = Resolve(symbol, "ylb_values_keyword");
            p_ylb_values_slot = Resolve(symbol, "ylb_values_slot");
            p_ylb_values_send = Resolve(symbol, "ylb_values_send");
            p_ylb_texture_send = Resolve(symbol, "ylb_texture_send");
            p_ylb_original_send = Resolve(symbol, "ylb_original_send");
            p_ylb_test_set_payload_limit = Resolve(symbol, "ylb_test_set_payload_limit");
            p_ylb_test_set_outbox_limit = Resolve(symbol, "ylb_test_set_outbox_limit");
            p_ylb_next_request = Resolve(symbol, "ylb_next_request");
            p_ylb_pending_bytes = Resolve(symbol, "ylb_pending_bytes");
            p_ylb_send_room = Resolve(symbol, "ylb_send_room");
            p_ylb_set_count = Resolve(symbol, "ylb_set_count");
            p_ylb_set_info = Resolve(symbol, "ylb_set_info");
            p_ylb_set_name = Resolve(symbol, "ylb_set_name");
            p_ylb_channel_dirty = Resolve(symbol, "ylb_channel_dirty");
            p_ylb_channel_mark_all_dirty = Resolve(symbol, "ylb_channel_mark_all_dirty");
            p_ylb_copy_dirty = Resolve(symbol, "ylb_copy_dirty");
            p_ylb_now_us = Resolve(symbol, "ylb_now_us");
            p_ylb_test_server_start = Resolve(symbol, "ylb_test_server_start");
            p_ylb_test_server_pause_reading = Resolve(symbol, "ylb_test_server_pause_reading");
            p_ylb_test_server_stop = Resolve(symbol, "ylb_test_server_stop");
            p_ylb_test_server_pattern = Resolve(symbol, "ylb_test_server_pattern");
            p_ylb_test_server_paint = Resolve(symbol, "ylb_test_server_paint");
            p_ylb_test_server_replace_key = Resolve(symbol, "ylb_test_server_replace_key");
            p_ylb_test_server_configure = Resolve(symbol, "ylb_test_server_configure");
            p_ylb_test_server_set_protocol = Resolve(symbol, "ylb_test_server_set_protocol");
            p_ylb_test_server_stats = Resolve(symbol, "ylb_test_server_stats");
            p_ylb_test_server_value = Resolve(symbol, "ylb_test_server_value");
            p_ylb_test_server_slot = Resolve(symbol, "ylb_test_server_slot");
            p_ylb_test_server_original = Resolve(symbol, "ylb_test_server_original");
            p_ylb_test_server_request = Resolve(symbol, "ylb_test_server_request");
            p_ylb_test_server_texture = Resolve(symbol, "ylb_test_server_texture");
        }

        static IntPtr Resolve(Func<string, IntPtr> symbol, string name)
        {
            var address = symbol(name);
            if (address == IntPtr.Zero) throw new EntryPointNotFoundException(name);
            return address;
        }

        /// <summary>結んでいない関数を呼んで、エディタを落とさない。</summary>
        static IntPtr Pointer(IntPtr address)
        {
            if (address == IntPtr.Zero) throw new InvalidOperationException("The Live Link library is not loaded.");
            return address;
        }
    }

    /// <summary>
    ///  版のずれと機能の印の様子（`ylb_link_report`）。版は `major &lt;&lt; 32 | minor &lt;&lt; 16 | patch`、不明は `u64::MAX`。
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct YlbLinkReport
    {
        /// <summary>
        ///  相手のアプリの版。
        /// </summary>
        public ulong peer_version;
        /// <summary>
        ///  相手が自分に求める版（相手が宣言していなければ不明）。
        /// </summary>
        public ulong peer_min_peer;
        /// <summary>
        ///  相手を上げるべきなら、求める版（`0` は版の指定なし）。上げなくてよければ不明。版を名乗らない古い相手は上げるべき。
        /// </summary>
        public ulong update_peer;
        /// <summary>
        ///  自分（Unity のパッケージ）を上げるべきなら、求める版。上げなくてよければ不明。
        /// </summary>
        public ulong update_self;
        /// <summary>
        ///  自分が出した機能の印・相手が出した印・共通部分（使える機能）。
        /// </summary>
        public ulong own_features;
        public ulong peer_features;
        public ulong common_features;
        /// <summary>
        ///  自分にあって相手に無い機能（相手を上げれば使える）・相手にあって自分に無い機能（自分を上げれば使える）。
        /// </summary>
        public ulong missing_on_peer;
        public ulong missing_here;
        /// <summary>
        ///  断られたとき（state 2）、上げるべき製品: 1 = Unity のパッケージ、2 = スタンドアロン。それ以外は 0。
        /// </summary>
        public int refused_update;
        /// <summary>
        ///  断られたときの、上げるべき製品の求める版（求める版が決まっていなければ不明）。
        /// </summary>
        public ulong refused_to;
        /// <summary>
        ///  断られたときの、Unity 側・スタンドアロンの読めるプロトコルの版の範囲。
        /// </summary>
        public uint unity_min_protocol;
        public uint unity_max_protocol;
        public uint standalone_min_protocol;
        public uint standalone_max_protocol;
        /// <summary>
        ///  0 = まだ無い（つないでいる・つなげなかった）、1 = つながった（上の欄を決めた）、2 = プロトコルの版の範囲が合わず断られた。
        /// </summary>
        public int state;
        /// <summary>
        ///  つながったときの、決まったプロトコルの版。
        /// </summary>
        public uint protocol;
    }

    /// <summary>
    ///  知らせ 1 つ。
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct YlbEvent
    {
        /// <summary>
        ///  1 = つながった、2 = 断られた、3 = 失敗、4 = 閉じた、5 = セットが来た、6 = セットが消えた、7 = 相手からの誤り、8 = こちらの知らせ。
        /// </summary>
        public int kind;
        public uint set;
        public int code;
        /// <summary>
        ///  説明の UTF-8 の長さ（領域が足りなければ切ってある）。
        /// </summary>
        public int text_len;
    }

    /// <summary>
    ///  スタンドアロンからの頼み 1 つ（`ylb_next_request`）。
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct YlbRequest
    {
        /// <summary>
        ///  頼みの世代（`ylb_model_send` の返した値。今のモデルの世代と違う頼みは、古いモデルのもの）。
        /// </summary>
        public uint generation;
        /// <summary>
        ///  モデルのマテリアルの番号。
        /// </summary>
        public uint material;
        /// <summary>
        ///  頼むもの（bit0 値・bit1 元の絵。知らない bit は無視する）。
        /// </summary>
        public uint wants;
        /// <summary>
        ///  スロットの名前の長さ（バイト。入りきらなければ要る長さ。元の絵でなければ 0）。
        /// </summary>
        public int slot_len;
        /// <summary>
        ///  スタンドアロンが手元に持つ元の絵の印（0 は持たない）。
        /// </summary>
        public ulong have;
    }

    /// <summary>
    ///  テクスチャセット 1 つの情報。
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct YlbSetInfo
    {
        public uint set;
        /// <summary>
        ///  どのモデルの世代のマテリアルか（ylb_model_send の返した値）。
        /// </summary>
        public uint generation;
        /// <summary>
        ///  モデルのマテリアルの番号。
        /// </summary>
        public uint material;
        public uint width;
        public uint height;
        public uint tile_size;
        /// <summary>
        ///  開けたチャンネルの印（1 &lt;&lt; チャンネル）。
        /// </summary>
        public uint channel_mask;
        /// <summary>
        ///  知らせを受け直すたびに変わる番号（変われば C# はテクスチャを作り直す）。
        /// </summary>
        public uint revision;
    }

    /// <summary>
    ///  写した結果。
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct YlbCopyResult
    {
        public uint tiles;
        /// <summary>
        ///  書いている途中だったので写さなかった（汚れたまま残した）タイル。
        /// </summary>
        public uint torn;
        /// <summary>
        ///  まだ汚れているタイル。
        /// </summary>
        public uint remaining;
        /// <summary>
        ///  写した画素の範囲（max は含まない。写していなければ全部 0）。
        /// </summary>
        public uint x_min;
        public uint y_min;
        public uint x_max;
        public uint y_max;
        /// <summary>
        ///  一番新しい知らせの、スタンドアロンが書き終えた時刻と、ブリッジが受けた時刻（UNIX のマイクロ秒）。
        /// </summary>
        public ulong stamp_us;
        public ulong received_us;
    }

    /// <summary>
    ///  自己診断のスタンドアロンが受けたものの数。
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct YlbTestServerStats
    {
        public uint connections;
        public uint models;
        public uint poses;
        /// <summary>
        ///  受けたポーズのメッシュの数の合計。
        /// </summary>
        public uint pose_meshes;
        /// <summary>
        ///  最後のモデルの世代・マテリアルの数・メッシュの数・頂点の数の合計。
        /// </summary>
        public uint generation;
        public uint materials;
        public uint meshes;
        public uint vertices;
        public uint models_closed;
        /// <summary>
        ///  断った（古い世代のポーズなど）・知らない・読めない命令の数。
        /// </summary>
        public uint refused;
        public uint unknown;
        /// <summary>
        ///  最後のポーズの、一番目のメッシュの一番目の頂点の位置（試験で見る）。
        /// </summary>
        public float last_pose_x;
        public float last_pose_y;
        public float last_pose_z;
        /// <summary>
        ///  受けたマテリアルの更新の数と、最後の更新のマテリアルの数・流し込み先の数の合計・一番目のマテリアルのシェーダー名の長さ。
        /// </summary>
        public uint materials_updates;
        public uint last_materials_count;
        public uint last_materials_routes;
        public uint last_materials_shader_len;
        /// <summary>
        ///  受けたマテリアルの値（MaterialValues）の数と、最後の値のマテリアルの番号・種類（0 値なし・1 lilToon）・プロパティの数・
        ///  キーワードの数・スロットの数・シェーダー名の長さ。
        /// </summary>
        public uint values;
        public uint last_values_material;
        public uint last_values_kind;
        public uint last_values_properties;
        public uint last_values_keywords;
        public uint last_values_slots;
        public uint last_values_shader_len;
        /// <summary>
        ///  受けた描いていないスロットの絵（MaterialTexture）の数と、その画素のバイトの合計（KiB、切り上げ）。
        /// </summary>
        public uint textures;
        public uint texture_kib;
        /// <summary>
        ///  受けた元の絵（MaterialOriginal）の数（絵の付かない様子も数える）と、絵の付いたものの画素のバイトの合計（KiB、切り上げ）。
        /// </summary>
        public uint originals;
        public uint original_kib;
        /// <summary>
        ///  元の絵が揃うまで出さずに待たせているセットの数（機能の印 ORIGINAL_TEXTURES を名乗っているときだけ待たせる）。
        /// </summary>
        public uint held_sets;
        /// <summary>
        ///  送った頼み（MaterialRequest。印 MATERIAL_REQUEST が双方にあるとき、待たせたセットの元の絵を自分から頼む分と、試験が頼ませた分）の数。
        /// </summary>
        public uint requests;
        /// <summary>
        ///  手元の絵を使った数（Cached の印が手元の絵と合った）と、使えなかった数（手元に無い・印か大きさが違う。頼み直す）。
        /// </summary>
        public uint cached_used;
        public uint cached_missed;
        /// <summary>
        ///  最後に送った頼みの、項目の数。
        /// </summary>
        public uint last_request_items;
        /// <summary>
        ///  最後に受けた元の絵（線の上で受けた様子。手元の絵に置き換える前）の様子（0 絵が付く・1 読めない・2 大きすぎる・3 予算・4 手元の絵を使う）と
        ///  マテリアルの番号。
        /// </summary>
        public uint last_original_state;
        public uint last_original_material;
    }

    /// <summary>
    ///  自己診断のスタンドアロンが受けた、元の絵 1 つの様子（`ylb_test_server_original`）。
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct YlbTestServerOriginal
    {
        /// <summary>
        ///  0 絵が付く・1 読めない・2 辺が上限を超える・3 予算を超える・4 手元の絵を使う（画素なし）。
        /// </summary>
        public uint state;
        /// <summary>
        ///  0 原本のファイル・1 取り込んだ絵・2 GPU を通して。
        /// </summary>
        public uint read;
        /// <summary>
        ///  0 でなければ圧縮されたテクスチャから読んだ。
        /// </summary>
        public uint compressed;
        /// <summary>
        ///  0 でなければ sRGB。
        /// </summary>
        public uint srgb;
        public uint width;
        public uint height;
        /// <summary>
        ///  真ん中の画素（(幅 / 2, 高さ / 2)。行は下から）と、一番下の左の画素の RGBA を r | g &lt;&lt; 8 | b &lt;&lt; 16 | a &lt;&lt; 24 に詰めたもの（絵が付かなければ 0）。
        /// </summary>
        public uint center;
        public uint corner;
        /// <summary>
        ///  絵の印（0 は印なし）。
        /// </summary>
        public ulong stamp;
    }

    /// <summary>
    ///  自己診断のスタンドアロンが受けた、描いていないスロットの絵 1 つの様子（`ylb_test_server_texture`）。
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct YlbTestServerTexture
    {
        public uint width;
        public uint height;
        /// <summary>
        ///  0 でなければ sRGB。
        /// </summary>
        public uint srgb;
        /// <summary>
        ///  真ん中の画素（(幅 / 2, 高さ / 2)。行は下から）の RGBA を r | g &lt;&lt; 8 | b &lt;&lt; 16 | a &lt;&lt; 24 に詰めたもの。
        /// </summary>
        public uint center;
    }



}
