// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace Yozolab.YoluPainter.Editor.LiveLink
{
    internal static unsafe partial class LiveLinkNative
    {
        const string __DllName = "yolu_bridge";





        /// <summary>
        ///  この口の版（最初に呼ぶ。C# の知っている版と違えば、ほかの関数を呼ばない）。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_abi_version", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern uint ylb_abi_version();

        /// <summary>
        ///  読めるプロトコルの版（上の 16 ビットが一番古い版、下の 16 ビットが一番新しい版）。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_protocol_versions", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern uint ylb_protocol_versions();

        /// <summary>
        ///  つなぎ始める（すぐに返る。つながったかは ylb_status と知らせで見る）。返すのはつながりの番号（0 は名前が使えない）。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_connect", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong ylb_connect(byte* name, int name_len, byte* agent, int agent_len);

        /// <summary>
        ///  `ylb_connect`（自分のアプリの版を挨拶で名乗る。Unity のパッケージの版の文字列「0.3.0」など。読めない・空なら名乗らない）。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_connect_with", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong ylb_connect_with(byte* name, int name_len, byte* agent, int agent_len, byte* app_version, int app_version_len);

        /// <summary>
        ///  切る（Bye を送る。共有メモリの写像を手放す）。番号はもう使えない。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_disconnect", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int ylb_disconnect(ulong handle);

        /// <summary>
        ///  全部のつながりを切る（ドメインの読み直しの後に、前のドメインのつながりを片付ける）。切った数を返す。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_disconnect_all", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int ylb_disconnect_all();

        /// <summary>
        ///  状態: 0 = つないでいる、1 = つながった、2 = 閉じた、3 = 失敗。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_status", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int ylb_status(ulong handle);

        /// <summary>
        ///  状態の説明（UTF-8）。要る長さを返す。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_status_text", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int ylb_status_text(ulong handle, byte* buf, int cap);

        /// <summary>
        ///  何かが変わるたびに増える番号（C# は変わっていなければ何もしない）。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_serial", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong ylb_serial(ulong handle);

        /// <summary>
        ///  このつながりで使える機能の印（双方が出した印の共通部分。つながるまでは 0）。印の要る新しい命令は、ここに立っているときだけ送る。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_common_features", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong ylb_common_features(ulong handle);

        /// <summary>
        ///  相手（スタンドアロン）のアプリの版（`major &lt;&lt; 32 | minor &lt;&lt; 16 | patch`）。つながっていない・版を名乗らない古い相手は `u64::MAX`。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_peer_app_version", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong ylb_peer_app_version(ulong handle);

        /// <summary>
        ///  版のずれと機能の印の様子を取り出す。返すのは `state`（0 = まだ無い、1 = つながった、2 = 版の範囲が合わず断られた）、負は失敗。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_link_report", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int ylb_link_report(ulong handle, YlbLinkReport* report);

        /// <summary>
        ///  知らせを 1 つ取り出す。取り出せば 1、無ければ 0。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_next_event", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int ylb_next_event(ulong handle, YlbEvent* @event, byte* buf, int cap);

        /// <summary>
        ///  モデルの組み立てを始める（前の組み立ては捨てる）。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_model_begin", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int ylb_model_begin(ulong handle, byte* name, int name_len);

        /// <summary>
        ///  マテリアルの組を足す。unassigned が 0 でなければマテリアルの無いスロットの組（名前・GUID は使わない）。guid_len が 0 ならアセットでない。
        ///  返すのはマテリアルの番号。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_model_material", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int ylb_model_material(ulong handle, int unassigned, byte* name, int name_len, byte* guid, int guid_len, long file_id, byte* shader, int shader_len);

        /// <summary>
        ///  マテリアルのシェーダーの 2D テクスチャのプロパティと、今入っているテクスチャの大きさ（無ければ 0）を足す。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_model_material_texture", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int ylb_model_material_texture(ulong handle, int material, byte* name, int name_len, uint width, uint height);

        /// <summary>
        ///  Unity 側が見せられるチャンネルと流し込み先のプロパティを足す。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_model_material_route", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int ylb_model_material_route(ulong handle, int material, int channel, byte* property, int property_len);

        /// <summary>
        ///  メッシュを足す（位置は根のローカルの空間。法線・UV0 は null なら無し）。返すのはメッシュの番号。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_model_mesh", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int ylb_model_mesh(ulong handle, byte* key, int key_len, byte* name, int name_len, int skinned, float* positions, float* normals, float* uv0, int vertex_count);

        /// <summary>
        ///  メッシュに三角形の組を足す（添字は 3 つずつ、頂点の数より小さい）。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_model_submesh", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int ylb_model_submesh(ulong handle, int mesh, int material, int* indices, int index_count);

        /// <summary>
        ///  組み立てたモデルを送る（積むだけ）。返すのはモデルの世代（1 から）。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_model_send", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int ylb_model_send(ulong handle);

        /// <summary>
        ///  送ったモデルを閉じる（スタンドアロンにもう見せないと知らせる）。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_model_close", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int ylb_model_close(ulong handle);

        /// <summary>
        ///  マテリアルの更新の組み立てを始める（前の組み立ては捨てる）。送ったモデルがあるときだけ。足すマテリアルの数と並びは、送ったモデルと同じにする。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_materials_begin", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int ylb_materials_begin(ulong handle);

        /// <summary>
        ///  更新のマテリアルの組を足す（`ylb_model_material` と同じ引数）。返すのはマテリアルの番号。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_materials_material", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int ylb_materials_material(ulong handle, int unassigned, byte* name, int name_len, byte* guid, int guid_len, long file_id, byte* shader, int shader_len);

        /// <summary>
        ///  更新のマテリアルにテクスチャのプロパティを足す。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_materials_texture", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int ylb_materials_texture(ulong handle, int material, byte* name, int name_len, uint width, uint height);

        /// <summary>
        ///  更新のマテリアルに、見せられるチャンネルと流し込み先を足す。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_materials_route", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int ylb_materials_route(ulong handle, int material, int channel, byte* property, int property_len);

        /// <summary>
        ///  組み立てたマテリアルの更新を送る（積むだけ）。マテリアルの数は送ったモデルと同じでなければならない（違えば YLB_E_ARGUMENT）。返すのはマテリアルの数。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_materials_send", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int ylb_materials_send(ulong handle);

        /// <summary>
        ///  ポーズの組み立てを始める。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_pose_begin", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int ylb_pose_begin(ulong handle);

        /// <summary>
        ///  メッシュの新しい形を足す（頂点の数は送ったモデルのそのメッシュと同じ）。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_pose_mesh", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int ylb_pose_mesh(ulong handle, int mesh, float* positions, float* normals, int vertex_count);

        /// <summary>
        ///  組み立てたポーズを送る（積むだけ。同じメッシュのまだ送っていない古いポーズは置き換える）。返すのは足したメッシュの数。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_pose_send", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int ylb_pose_send(ulong handle);

        /// <summary>
        ///  テクスチャセットの数。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_set_count", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int ylb_set_count(ulong handle);

        /// <summary>
        ///  index 番目（セットの番号の順）のテクスチャセットの情報。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_set_info", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int ylb_set_info(ulong handle, int index, YlbSetInfo* info);

        /// <summary>
        ///  テクスチャセットの名前。要る長さを返す。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_set_name", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int ylb_set_name(ulong handle, uint set, byte* buf, int cap);

        /// <summary>
        ///  チャンネルの汚れたタイルの数。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_channel_dirty", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int ylb_channel_dirty(ulong handle, uint set, int channel);

        /// <summary>
        ///  チャンネルの全部のタイルを汚れたことにする（Unity 側のテクスチャを作り直した・失ったとき、次の ylb_copy_dirty で全面を写し直す）。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_channel_mark_all_dirty", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int ylb_channel_mark_all_dirty(ulong handle, uint set, int channel);

        /// <summary>
        ///  汚れたタイルを image（幅 × 高さ × 4 バイト、straight RGBA8、下の行から。Unity の Texture2D の RGBA32 の生の並び）へ写す。
        ///  strip が null でなければ、strip_tiles 個までのタイルを帯（幅 strip_tiles × タイル、高さ タイル、下の行から）にも並べ、
        ///  coords（2 × strip_tiles 個）にタイルの座標を書いて、そこで止める（残りは次に）。返すのは写したタイルの数。
        ///  image は null でもよい（strip が要る）: 全体を GPU のテクスチャ（RenderTexture）に持つ側が、CPU に全体の写しを持たずに帯だけを受ける。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_copy_dirty", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int ylb_copy_dirty(ulong handle, uint set, int channel, byte* image, ulong image_len, byte* strip, ulong strip_len, int strip_tiles, uint* coords, YlbCopyResult* result);

        /// <summary>
        ///  UNIX 時刻のマイクロ秒（スタンドアロン・ブリッジと同じ時計で遅れを測る）。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_now_us", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong ylb_now_us();

        /// <summary>
        ///  試しの模様を返すスタンドアロンを、このプロセスの中で待ち受けさせる。モデルが来ると、マテリアルごとに size × size のセット
        ///  （Color と、流し込み先のあるチャンネル）を作り、ylb_test_server_pattern の模様を全部のタイルに書いて知らせる。返すのは番号（0 は失敗）。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_test_server_start", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong ylb_test_server_start(byte* name, int name_len, int size, int tile_size);

        /// <summary>
        ///  自己診断のスタンドアロンを止める（つないでいる側を先に切る。Windows では相手が切るまで読むスレッドが残る）。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_test_server_stop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int ylb_test_server_stop(ulong server);

        /// <summary>
        ///  模様の色（RGBA を r | g &lt;&lt; 8 | b &lt;&lt; 16 | a &lt;&lt; 24 に詰めたもの）: マテリアルの番号ごとの色の市松（奇数のタイルは半分の明るさ）。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_test_server_pattern", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern uint ylb_test_server_pattern(uint material, uint tile_x, uint tile_y);

        /// <summary>
        ///  自己診断のスタンドアロンで、material の番号のセットの channel の、タイル [x0, x1) × [y0, y1) を色 rgba（ylb_test_server_pattern
        ///  と同じ詰め方）で塗り、変わったタイルを知らせる。返すのは塗ったタイルの数。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_test_server_paint", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int ylb_test_server_paint(ulong server, uint material, int channel, uint x0, uint y0, uint x1, uint y1, uint rgba);

        /// <summary>
        ///  自己診断のスタンドアロンの鍵のファイルを、別の鍵に差し替える（つなぎ直すブリッジは、鍵の合わない断りを受ける）。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_test_server_replace_key", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int ylb_test_server_replace_key(ulong server);

        /// <summary>
        ///  自己診断のスタンドアロンの名乗りを決める（次につなぐブリッジから効く）。`app_version`・`min_peer` は `major &lt;&lt; 32 | minor &lt;&lt; 16 | patch`
        ///  （`u64::MAX` は版を名乗らない古いスタンドアロンの役）、`features` は出す機能の印。既定はこの DLL の版・要求なし・印なし。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_test_server_configure", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int ylb_test_server_configure(ulong server, ulong app_version, ulong min_peer, ulong features);

        /// <summary>
        ///  自己診断のスタンドアロンの読めるプロトコルの版の範囲を決める（次につなぐブリッジから効く。ブリッジの範囲と重ならなければ、版の範囲の断りを返す）。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_test_server_set_protocol", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int ylb_test_server_set_protocol(ulong server, uint min, uint max);

        /// <summary>
        ///  自己診断のスタンドアロンが受けたものの数。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ylb_test_server_stats", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int ylb_test_server_stats(ulong server, YlbTestServerStats* stats);


    }

    /// <summary>
    ///  版のずれと機能の印の様子（`ylb_link_report`）。版は `major &lt;&lt; 32 | minor &lt;&lt; 16 | patch`、不明は `u64::MAX`。
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct YlbLinkReport
    {
        /// <summary>
        ///  相手のアプリの版。
        /// </summary>
        public ulong peer_version;
        /// <summary>
        ///  相手が自分に求める版（相手が宣言していなければ不明）。
        /// </summary>
        public ulong peer_min_peer;
        /// <summary>
        ///  相手を上げるべきなら、求める版（`0` は版の指定なし）。上げなくてよければ不明。版を名乗らない古い相手は上げるべき。
        /// </summary>
        public ulong update_peer;
        /// <summary>
        ///  自分（Unity のパッケージ）を上げるべきなら、求める版。上げなくてよければ不明。
        /// </summary>
        public ulong update_self;
        /// <summary>
        ///  自分が出した機能の印・相手が出した印・共通部分（使える機能）。
        /// </summary>
        public ulong own_features;
        public ulong peer_features;
        public ulong common_features;
        /// <summary>
        ///  自分にあって相手に無い機能（相手を上げれば使える）・相手にあって自分に無い機能（自分を上げれば使える）。
        /// </summary>
        public ulong missing_on_peer;
        public ulong missing_here;
        /// <summary>
        ///  断られたとき（state 2）、上げるべき製品: 1 = Unity のパッケージ、2 = スタンドアロン。それ以外は 0。
        /// </summary>
        public int refused_update;
        /// <summary>
        ///  断られたときの、上げるべき製品の求める版（求める版が決まっていなければ不明）。
        /// </summary>
        public ulong refused_to;
        /// <summary>
        ///  断られたときの、Unity 側・スタンドアロンの読めるプロトコルの版の範囲。
        /// </summary>
        public uint unity_min_protocol;
        public uint unity_max_protocol;
        public uint standalone_min_protocol;
        public uint standalone_max_protocol;
        /// <summary>
        ///  0 = まだ無い（つないでいる・つなげなかった）、1 = つながった（上の欄を決めた）、2 = プロトコルの版の範囲が合わず断られた。
        /// </summary>
        public int state;
        /// <summary>
        ///  つながったときの、決まったプロトコルの版。
        /// </summary>
        public uint protocol;
    }

    /// <summary>
    ///  知らせ 1 つ。
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct YlbEvent
    {
        /// <summary>
        ///  1 = つながった、2 = 断られた、3 = 失敗、4 = 閉じた、5 = セットが来た、6 = セットが消えた、7 = 相手からの誤り、8 = こちらの知らせ。
        /// </summary>
        public int kind;
        public uint set;
        public int code;
        /// <summary>
        ///  説明の UTF-8 の長さ（領域が足りなければ切ってある）。
        /// </summary>
        public int text_len;
    }

    /// <summary>
    ///  テクスチャセット 1 つの情報。
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct YlbSetInfo
    {
        public uint set;
        /// <summary>
        ///  どのモデルの世代のマテリアルか（ylb_model_send の返した値）。
        /// </summary>
        public uint generation;
        /// <summary>
        ///  モデルのマテリアルの番号。
        /// </summary>
        public uint material;
        public uint width;
        public uint height;
        public uint tile_size;
        /// <summary>
        ///  開けたチャンネルの印（1 &lt;&lt; チャンネル）。
        /// </summary>
        public uint channel_mask;
        /// <summary>
        ///  知らせを受け直すたびに変わる番号（変われば C# はテクスチャを作り直す）。
        /// </summary>
        public uint revision;
    }

    /// <summary>
    ///  写した結果。
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct YlbCopyResult
    {
        public uint tiles;
        /// <summary>
        ///  書いている途中だったので写さなかった（汚れたまま残した）タイル。
        /// </summary>
        public uint torn;
        /// <summary>
        ///  まだ汚れているタイル。
        /// </summary>
        public uint remaining;
        /// <summary>
        ///  写した画素の範囲（max は含まない。写していなければ全部 0）。
        /// </summary>
        public uint x_min;
        public uint y_min;
        public uint x_max;
        public uint y_max;
        /// <summary>
        ///  一番新しい知らせの、スタンドアロンが書き終えた時刻と、ブリッジが受けた時刻（UNIX のマイクロ秒）。
        /// </summary>
        public ulong stamp_us;
        public ulong received_us;
    }

    /// <summary>
    ///  自己診断のスタンドアロンが受けたものの数。
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct YlbTestServerStats
    {
        public uint connections;
        public uint models;
        public uint poses;
        /// <summary>
        ///  受けたポーズのメッシュの数の合計。
        /// </summary>
        public uint pose_meshes;
        /// <summary>
        ///  最後のモデルの世代・マテリアルの数・メッシュの数・頂点の数の合計。
        /// </summary>
        public uint generation;
        public uint materials;
        public uint meshes;
        public uint vertices;
        public uint models_closed;
        /// <summary>
        ///  断った（古い世代のポーズなど）・知らない・読めない命令の数。
        /// </summary>
        public uint refused;
        public uint unknown;
        /// <summary>
        ///  最後のポーズの、一番目のメッシュの一番目の頂点の位置（試験で見る）。
        /// </summary>
        public float last_pose_x;
        public float last_pose_y;
        public float last_pose_z;
        /// <summary>
        ///  受けたマテリアルの更新の数と、最後の更新のマテリアルの数・流し込み先の数の合計・一番目のマテリアルのシェーダー名の長さ。
        /// </summary>
        public uint materials_updates;
        public uint last_materials_count;
        public uint last_materials_routes;
        public uint last_materials_shader_len;
    }



}
